/* eslint-disable @next/next/no-html-link-for-pages */
import { Index } from "@/components/Index";
import Mynavbar from "@/components/Navbar";
import Head from "next/head";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mynavbar />
      <Index />
    </>
  );
}
